import { Friend } from "./friends.model";

export const friendsData:Friend[]=[
    {
        id:1,
        firstName:"Roman",
        lastName:"Shah"
    },
    {
        id:2,
        firstName:"Parth",
        lastName:"Gujjar"
    },
    {
        id:3,
        firstName:"Aman",
        lastName:"Badola"
    },
    {
        id:4,
        firstName:"Arvind",
        lastName:"Raghavan"
    },
    {
        id:5,
        firstName:"Mukul",
        lastName:"Singh"
    },
    {
        id:6,
        firstName:"Diamond",
        lastName:"Robert"
    },
    {
        id:7,
        firstName:"Absar",
        lastName:"Sharique"
    },
    {
        id:8,
        firstName:"Aman",
        lastName:"Jain"
    }
];